language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=docs

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov --env TRAVIS_OS_NAME,TOXENV
